x=input('Digite algo:')
print('O tipo primitivo de',x,'e',type(x))
print('So tem espaços?',(x.isspace()))
print('E um numero?',(x.isnumeric()))
print('E alfabetico?',(x.isalpha()))
print('E alfanumerico?',(x.isalnum()))
print('Esta em maiusculas?',(x.isupper()))
print('Esta em minusculas?',(x.islower()))
print('Esta capitalizado?',(x.istitle()))
