nomes=('João','Tiago','Maria','Sanchez','Roldrigo','Camilla','Normani','Pablo','Pedro','Hal','Marcos','Hilário','Diana','Clark','Bruce','Artur','Victor','Barry','Mobius','Kent')
print(nomes[0:5])
print('='*50)
print(nomes[-4:])
print('='*50)
print(sorted(nomes))
print('='*50)
x=nomes.index('Maria')
print(f'{x}ª Posição.')
